cache:
  paths:
    - cache/

stages:
  - snapshot
  - sonar
  - release

snapshot:
  image: registry.agillic.net/operations/docker-gradle-jdk8:latest
  stage: snapshot
  script:
    - 'env'
    - './gradlew install'

  image: registry.agillic.net/operations/docker-gradle-jdk8:latest
  stage: sonar
  script:
    - './gradle test'
  only:
    - master

release:
  image: registry.agillic.net/operations/docker-gradle-jdk8:latest
  stage: release
  script:
    - 'echo releasing' 
  only:
    - tags
  except:
    - /\d+\.\d+\.\d+-.*/
    - branches
  artifacts:
    expire_in: 1 week
    paths:
      - target/
