variables:
  S3_MAX_AGE: "600"
  S3_MAX_AGE_HEADER: "--add-header 'Cache-Control: max-age=600' "
  S3_STAG_ACCESS: "--access_key=${STAG_S3_ACCESS_KEY} --secret_key=${STAG_S3_SECRET_KEY}"
  S3_STAG_URL: "s3://agillic-devportal-staging/sdk"
  S3_PROD_ACCESS: "--access_key=${PROD_S3_ACCESS_KEY} --secret_key=${PROD_S3_SECRET_KEY}"
  S3_PROD_URL: "s3://agillic-devportal-production/"
  
stages:
- build
- deploy
- snapshot
- release

before_script:
- export GRADLE_USER_HOME=$(pwd)/.gradle
- chmod +x ./gradlew

cache:
  key: ${CI_PROJECT_ID}
  paths:
  - .gradle/

build:
  image: registry.agillic.net/development-tools/gitlab-ci-android
  stage: build
  script:
  - ./gradlew assembleDebug
  artifacts:
    expire_in: 1 day
    paths:
    - app/build/outputs/apk/
    - agillic-android-sdk/build/outputs/aar/

snapshot:
  image: registry.agillic.net/development-tools/gitlab-ci-android
  stage: snapshot
  script:
    - 'env'
    - './gradlew install'
  artifacts:
    expire_in: 10 mins
    paths:
    - app/build/outputs/apk/
    - agillic-android-sdk/build/outputs/aar/

deploy_s3_stag:
  image: registry.agillic.net/operations/s3cmd:latest
  stage: deploy
  script:
    - 'echo ${S3_STAG_ACCESS}'
    - 's3cmd ${S3_STAG_ACCESS} put agillic-android-sdk/build/outputs/aar/*.aar --add-header "Cache-Control: max-age=600" ${S3_STAG_URL}/sdk/'
    - 's3cmd ${S3_STAG_ACCESS} setacl --acl-public --recursive ${S3_STAG_URL}/sdk/'
  only:
    - master
    

release:
  image: registry.agillic.net/development-tools/gitlab-ci-android
  stage: release
  script:
    - 'echo releasing' 
  only:
    - tags
  except:
    - /\d+\.\d+\.\d+-.*/
    - branches
  artifacts:
    expire_in: 1 week
    paths:
      - target/
