image: registry.agillic.net/development-tools/gitlab-ci-android

stages:
- build
- snapshot
- release

before_script:
- export GRADLE_USER_HOME=$(pwd)/.gradle
- chmod +x ./gradlew

cache:
  key: ${CI_PROJECT_ID}
  paths:
  - .gradle/

build:
  stage: build
  script:
  - ./gradlew assembleDebug
  artifacts:
    paths:
    - app/build/outputs/apk/
    - agillic-android-sdk/build/outputs/aar/

snapshot:
  stage: snapshot
  script:
    - 'env'
    - './gradlew install'

release:
  stage: release
  script:
    - 'echo releasing' 
  only:
    - tags
  except:
    - /\d+\.\d+\.\d+-.*/
    - branches
  artifacts:
    expire_in: 1 week
    paths:
      - target/
